---
driver:
  name: docker
  driver_config:
    use_sudo: false

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 14
  deprecations_as_errors: true
  multiple_converge: 2
  enforce_idempotency: true
  attributes:
    fluentbit:
      conf:
        Daemon: "On"

verifier:
  name: inspec

platforms:
  - name: debian
  - name: ubuntu
  - name: ubuntu-18.04

suites:
  - name: default
    run_list:
      - recipe[fluentbit::install]
      - recipe[fluentbit::_example]
    attributes:
      fluentbit:
        install_mode: "package"
  - name: source
    run_list:
      - recipe[fluentbit::install]
      - recipe[fluentbit::_example]
    attributes:
      fluentbit:
        install_mode: "source"