language: ruby
sudo: required
dist: focal
group: edge # https://github.com/travis-ci/travis-ci/issues/5448
services:
  - docker
rvm:
  - 3.0.1
  - 2.7.3
  - 2.6.7
before_install:
  - gem update --system # https://github.com/travis-ci/travis-ci/issues/8978
  - gem --version
script:
  - bundle exec rake
